Mesure/src/main/java/com/mesure/controller/CadastroTituloReceberBean.java
package com.mesure.controller;

import com.mesure.enumerator.ESimNao;
import com.mesure.enumerator.EStatusProjeto;
import com.mesure.enumerator.EStatusTitulo;
import com.mesure.model.Cliente;
import com.mesure.model.ContaBancaria;
import com.mesure.model.Empresa;
import com.mesure.model.Filial;
import com.mesure.model.Projeto;
import com.mesure.model.TituloReceber;
import com.mesure.model.TituloReceberBaixa;
import com.mesure.repository.ClienteRepository;
import com.mesure.repository.ContaBancariaRepository;
import com.mesure.repository.EmpresaRepository;
import com.mesure.repository.ProjetoRepository;
import com.mesure.repository.filter.EmpresaFilter;
import com.mesure.repository.filter.ProjetoFilter;
import com.mesure.security.Seguranca;
import com.mesure.security.UsuarioLogado;
import com.mesure.security.UsuarioSistema;
import com.mesure.service.NegocioException;
import com.mesure.service.TituloReceberService;
import com.mesure.util.jsf.FacesUtil;
import java.io.Serializable;
import java.math.BigDecimal;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import org.apache.commons.lang3.StringUtils;

@Named
@ViewScoped
public class CadastroTituloReceberBean implements Serializable {

    private static final long serialVersionUID = 1L;

    @Inject
    private TituloReceberService tituloReceberService;

    @Inject
    EmpresaRepository empresaRepository;

    @Inject
    ClienteRepository clienteRepository;

    @Inject
    ContaBancariaRepository contaBancariaRepository;

    @Inject
    private ProjetoRepository projetoRepository;

    @Inject
    private HttpServletRequest request;

    @Inject
    Seguranca seguranca;

    @Inject
    @UsuarioLogado
    private UsuarioSistema usuarioLogado;

    private TituloReceber tituloReceber;

    private Empresa empresa;
    private Cliente cliente;

    private List<Empresa> empresas;
    private List<Filial> filiais;
    private List<Projeto> projetos;
    private List<Cliente> clientes;
    private List<ContaBancaria> contasBancaria;

    private TituloReceberBaixa tituloReceberBaixa;

    private Long idProjeto;
    private Date dataMovimentoEstornar;

    public CadastroTituloReceberBean() {
        limpar();
    }

    public void inicializar() {
        String param_tituloReceber = request.getParameter("tituloReceber");

        if (StringUtils.isBlank(param_tituloReceber)) {
            tituloReceber = null;
        }

        // Verifica se a filial do projeto é a filial ativa
        if (tituloReceber != null && tituloReceber.isEditando()) {
            if (!tituloReceber.getFilial().equals(usuarioLogado.getFilialAtiva())) {
                tituloReceber = null;
            }
        }

        if (tituloReceber == null) {
            limpar();
        }

        // Carrega os projetos em aberto
        carregarProjetos();

        // carrega todas as empresas cadastradas
        empresas = empresaRepository.empresas(new EmpresaFilter());

        // Carrega todos os clientes cadastrados
        clientes = clienteRepository.clientes();

        // Se é um novo projeto, ou seja, modo de inclusão
        if (tituloReceber != null && !tituloReceber.isEditando()) {
            tituloReceber.setStatus(EStatusTitulo.ABERTO);
            empresa = usuarioLogado.getFilialAtiva().getEmpresa();
            tituloReceber.setFilial(usuarioLogado.getFilialAtiva());
        }

        // Carrega as filiais da empresa para apresentar no formulário
        if (empresa != null) {
            carregarFiliais();
        }

        // Carrega o cliente vinculado ao projeto, para que já fique selecionado na tela
        cliente = null;
        if (tituloReceber.isEditando()) {
            cliente = tituloReceber.getProjeto().getCliente();
        }

        idProjeto = new Long(0);
    }

    private void limpar() {
        tituloReceber = new TituloReceber();

        idProjeto = new Long(0);
        empresa = null;
        filiais = null;

        limparBaixa();
    }

    public void excluirBaixa() {
        if (tituloReceberBaixa != null) {
            tituloReceber.getBaixas().remove(tituloReceberBaixa);
        }
    }

    public void salvar() {
        tituloReceber = tituloReceberService.salvar(tituloReceber);

        FacesUtil.addInfoMessageGrowl("Gravação efetuada com sucesso.");
    }

    public boolean isHabilitaBotaoGravar() {
        return tituloReceber.getStatus() == EStatusTitulo.ABERTO;
    }

    public void carregarFiliais() {
        filiais = null;

        if (empresa != null) {
            filiais = empresaRepository.filialDe(empresa);
        }
    }

    public void onChangeEmpresa() {
        carregarFiliais();
    }

    public void onChangeCBCliente() {
        tituloReceber.setProjeto(null);
        carregarProjetos();

        if (projetos.isEmpty()) {
            FacesUtil.addWarnMessage("O cliente informado não possui projetos cadastrados.");
        }
    }

    public void limparBaixa() {
        tituloReceberBaixa = new TituloReceberBaixa();
    }

    // Para carregar as opções do Enum no formulário
    public EStatusTitulo[] getStatus() {
        return EStatusTitulo.values();
    }

    public TituloReceber getTituloReceber() {
        return tituloReceber;
    }

    public void setTituloReceber(TituloReceber tituloReceber) {
        this.tituloReceber = tituloReceber;

        if (this.tituloReceber != null) {
            this.empresa = this.tituloReceber.getFilial().getEmpresa();
        }
    }

    public void incluirBaixa() throws ParseException {
        tituloReceberService.consistirBaixaTituloReceber(tituloReceberBaixa);

        if (!tituloReceber.getBaixas().contains(tituloReceberBaixa)) {
            tituloReceberBaixa.setTitulo(tituloReceber);
            tituloReceberBaixa.setValorLiquido(tituloReceberService.getValorLiquidoTituloReceberBaixa(tituloReceberBaixa));
            tituloReceber.getBaixas().add(tituloReceberBaixa);
            limparBaixa();
        }
    }

    public void carregarProjetos() {
        ProjetoFilter projetoFilter = new ProjetoFilter();
        // Somente projetos em aberto
        EStatusProjeto[] statuses = {EStatusProjeto.COMECAR, EStatusProjeto.ANDAMENTO, EStatusProjeto.ATV_EXTERNA};
        projetoFilter.setStatuses(statuses);
        if (usuarioLogado.getFilialAtiva().getFiltrarProjetos().equals(ESimNao.SIM)) {
            projetoFilter.setFilial(usuarioLogado.getFilialAtiva());
        }
        projetoFilter.setCliente(cliente);
        projetoFilter.setPropriedadeOrdenacao("titulo");
        projetos = projetoRepository.filtrados(projetoFilter);

        if (tituloReceber != null) {
            if (tituloReceber.getProjeto() != null && tituloReceber.getProjeto().getId() != null) {
                idProjeto = tituloReceber.getProjeto().getId();
            } else {
                idProjeto = new Long(0);
            }
        }
    }

    public void onChangeCBProjeto() {
        if (tituloReceber.getProjeto() != null) {
            idProjeto = tituloReceber.getProjeto().getId();
        } else {
            idProjeto = new Long(0);
        }
    }

    public void consultarProjetoId() {
        if (idProjeto != null && idProjeto != 0) {
            tituloReceber.setProjeto(projetoRepository.porId(idProjeto));

            if (tituloReceber.getProjeto() == null || (!projetos.contains(tituloReceber.getProjeto()))) {
                idProjeto = new Long(0);
                tituloReceber.setProjeto(null);
            }
        } else {
            idProjeto = new Long(0);
            tituloReceber.setProjeto(null);
        }
    }

    public void onChangeIdProjeto() {
        consultarProjetoId();
    }

    public void onChangeValoresBaixa() {
        tituloReceberBaixa.setValorLiquido(tituloReceberService.getValorLiquidoTituloReceberBaixa(tituloReceberBaixa));
    }

    public void inicializarBaixa() {
        tituloReceberBaixa.setTitulo(tituloReceber);
        tituloReceberBaixa.setDataBaixa(new Date());
        tituloReceberBaixa.setDataMovimento(new Date());
        tituloReceberBaixa.setValorBaixa(tituloReceber.getSaldo());
        tituloReceberBaixa.setValorAcrescimo(BigDecimal.ZERO);
        tituloReceberBaixa.setValorDesconto(BigDecimal.ZERO);
        tituloReceberBaixa.setValorJuros(BigDecimal.ZERO);
        tituloReceberBaixa.setValorMulta(BigDecimal.ZERO);
        tituloReceberBaixa.setValorLiquido(BigDecimal.ZERO);

        contasBancaria = contaBancariaRepository.obterContasBancarias(tituloReceber.getFilial());
    }

    public void estornarBaixa() throws ParseException {
        if (dataMovimentoEstornar != null) {
            List<TituloReceberBaixa> baixasList = new ArrayList<>();

            for (TituloReceberBaixa baixas : tituloReceber.getBaixas()) {
                if (baixas.isFlag() && baixas.getValorBaixa().doubleValue() > 0) {
                    if (dataMovimentoEstornar.before(baixas.getDataMovimento())) {
                        throw new NegocioException("Data do movimento não pode ser anterior a data do movimento da baixa de origem.");
                    }

                    TituloReceberBaixa baixaEstorno = new TituloReceberBaixa();

                    baixaEstorno.setContaBancaria(baixas.getContaBancaria());
                    baixaEstorno.setDataBaixa(baixas.getDataBaixa());
                    baixaEstorno.setDataMovimento(dataMovimentoEstornar);
                    baixaEstorno.setFlag(false);
                    baixaEstorno.setValorAcrescimo(new BigDecimal(baixas.getValorAcrescimo().doubleValue() * -1));
                    baixaEstorno.setValorBaixa(new BigDecimal(baixas.getValorBaixa().doubleValue() * -1));
                    baixaEstorno.setValorDesconto(new BigDecimal(baixas.getValorDesconto().doubleValue() * -1));

Mesure/src/main/java/com/mesure/controller/PesquisaTituloReceberBean.java
package com.mesure.controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.mesure.model.TituloReceber;
import com.mesure.repository.TituloReceberRepository;
import com.mesure.repository.filter.TituloReceberFilter;
import com.mesure.security.Seguranca;
import com.mesure.security.UsuarioLogado;
import com.mesure.security.UsuarioSistema;

@Named
@ViewScoped
public class PesquisaTituloReceberBean implements Serializable {

    private static final long serialVersionUID = 1L;

    @Inject
    TituloReceberRepository tituloReceberRepository;

    @Inject
    Seguranca seguranca;

    @Inject
    @UsuarioLogado
    private UsuarioSistema usuarioLogado;

    private TituloReceberFilter filtro;
    private List<TituloReceber> tituloReceberFiltrados;

    public PesquisaTituloReceberBean() {
        filtro = new TituloReceberFilter();
    }

    @PostConstruct
    public void inicializar() {

    }

    public void pesquisar() {
        if (filtro == null) {
            filtro = new TituloReceberFilter();
        }

        // Para trazer somente titulos da filial ativa
        filtro.setFilial(usuarioLogado.getFilialAtiva());

        tituloReceberFiltrados = tituloReceberRepository.filtrados(filtro);
    }

    public TituloReceberFilter getFiltro() {
        return filtro;
    }

    public List<TituloReceber> getTituloReceberFiltrados() {
        return tituloReceberFiltrados;
    }

}

Mesure/src/main/webapp/financeiro/LoteFaturamentoDetalhe.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:o="http://omnifaces.org/ui"
    xmlns:b="http://bootsfaces.net/ui">

    <ui:define name="titulo">Lote detalhe</ui:define>
    
    <ui:define name="corpo">
        <f:metadata>
        	<o:viewParam name="lote" value="#{detalheLoteFaturamentoBean.lote}" converter="faturamentoLoteConverter" />
			<f:viewAction action="#{detalheLoteFaturamentoBean.inicializar}"></f:viewAction>
		</f:metadata>
		
		<script>

		</script>		
		
   	    <h:form id="frmCadastro">
   	    
	   		<b:container fluid="true">
	   		
	   		<h3>Detalhamento do lote: #{detalheLoteFaturamentoBean.lote.descricao}</h3>
	   		
	   		<b:messages id="mensagens" info-class="message-info-hidden" />
	   		<p:growl autoUpdate="true" for="message-growl" life="2000" showDetail="true" showSummary="false" />

	    	<b:panel rendered="#{detalheLoteFaturamentoBean.carregouRegistros}">
				<b:button value="Fechar" outcome="/financeiro/LoteFaturamento" look="primary" style="float: right" size="sm" />
					    	
   				<b:commandButton disabled="#{!detalheLoteFaturamentoBean.podeFecharLote}" value="Fechar lote" id="btn-fechar-lote" action="#{detalheLoteFaturamentoBean.fecharLote}" look="primary" 
   					process="@this" update="@this btn-liberar-lote mensagens" size="sm"/>
	    				
   				<p:spacer width="10"/>
   				<b:commandButton disabled="#{!detalheLoteFaturamentoBean.podeLiberarLote}" value="Liberar lote" id="btn-liberar-lote" action="#{detalheLoteFaturamentoBean.liberarLote}" look="primary" 
   					process="@this" update="@this btn-fechar-lote mensagens" size="sm"/>   				
	    	</b:panel>
	    	
			<b:dataTable rendered="#{detalheLoteFaturamentoBean.carregouRegistros}" id="detalhesTable" value="#{detalheLoteFaturamentoBean.lote.detalhes}" var="detalhe" customLangUrl="#{resource['/json/pt-br.json']}"
				pageLength="1000" pageLengthMenu="[10,25,50,100,250,500,1000]"
				columnVisibility="true" excel="true" pdf="true" copy="true" print="true" scrollX="true">
				
				<b:dataTableColumn label="Colaborador" value="#{detalhe.colaborador.nome}"/>
   				<b:dataTableColumn label="Data" dataType="date" data-order="#{detalhe.data.toString()}">
   					<h:outputText value="#{detalhe.data}">
	    				<f:convertDateTime pattern="dd/MM/yyyy" />
   					</h:outputText>	    				
   				</b:dataTableColumn>		
	    		<b:dataTableColumn label="Dia semana" value="#{detalhe.diaSemana.label}"/>
   				<b:dataTableColumn label="Início" styleClass="coluna-centro">
   					<h:outputText value="#{detalhe.horaInicio}">
	    				<f:convertDateTime type="time" timeStyle="short" />
   					</h:outputText>
   				</b:dataTableColumn>
   				<b:dataTableColumn label="Fim" styleClass="coluna-centro">
   					<h:outputText value="#{detalhe.horaFim}">
	    				<f:convertDateTime type="time" timeStyle="short" />
   					</h:outputText>
   				</b:dataTableColumn>
   				<b:dataTableColumn label="Início noturno" styleClass="coluna-centro">
   					<h:outputText value="#{detalhe.horaInicioNoturno}">
	    				<f:convertDateTime type="time" timeStyle="short" />
   					</h:outputText>
   				</b:dataTableColumn>
   				<b:dataTableColumn label="Fim noturno" styleClass="coluna-centro">
   					<h:outputText value="#{detalhe.horaFimNoturno}">
	    				<f:convertDateTime type="time" timeStyle="short" />
   					</h:outputText>
   				</b:dataTableColumn>
   				<b:dataTableColumn label="Início extra" styleClass="coluna-centro">
   					<h:outputText value="#{detalhe.horaInicioExtra}">
	    				<f:convertDateTime type="time" timeStyle="short" />
   					</h:outputText>
   				</b:dataTableColumn>
   				<b:dataTableColumn label="Fim extra" styleClass="coluna-centro">
   					<h:outputText value="#{detalhe.horaFimExtra}">
	    				<f:convertDateTime type="time" timeStyle="short" />
   					</h:outputText>
   				</b:dataTableColumn>
    			<b:dataTableColumn label="Total" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.totalHoras}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
    			<b:dataTableColumn label="Total noturno" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.totalHorasNoturno}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
    			<b:dataTableColumn label="Total extra" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.totalHorasExtra}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
    			<b:dataTableColumn label="Valor cobrança" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.valorCobranca}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
    			<b:dataTableColumn label="Valor cobrança noturna" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.valorCobrancaNoturna}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
    			<b:dataTableColumn label="Valor 50%" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.valor50}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
    			<b:dataTableColumn label="Valor 100%" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.valor100}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
    			<b:dataTableColumn label="Total cobrança" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.totalCobranca}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
    			<b:dataTableColumn label="Total cobrança noturna" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.totalCobrancaNoturna}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
    			<b:dataTableColumn label="Total cobrança 100%" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.totalCobranca100}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
    			<b:dataTableColumn label="Total geral" styleClass="coluna-centro">
    				<h:outputText value="#{detalhe.totalGeral}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
			</b:dataTable>
					
			</b:container>	
		</h:form>	
    </ui:define>
</ui:composition>

Mesure/src/main/webapp/financeiro/PesquisaTituloReceber.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:b="http://bootsfaces.net/ui">

    <ui:define name="titulo">Titulos Receber</ui:define>

    <ui:define name="corpo">

        <h:form id="frmpesquisa">

            <b:container fluid="true">	    		    	
                <b:messages id="mensagens" styleClass="mensagens"/>

                <b:defaultCommand target="pesquisar" />

                <br/>
                <b:panel>
                    <b:commandButton value="Mostrar" id="pesquisar" action="#{pesquisaTituloReceberBean.pesquisar}" look="primary" update="tituloReceberTable" size="sm" />
                    <p:spacer width="10"/>
                    <b:button value="Novo titulo a receber" outcome="/financeiro/CadastroTituloReceber" look="primary" size="sm" />
                </b:panel>

                <b:dataTable id="tituloReceberTable" styleClass="tituloReceberTable" value="#{pesquisaTituloReceberBean.tituloReceberFiltrados}" var="tituloReceber" customLangUrl="#{resource['/json/pt-br.json']}"
                             pageLength="50" pageLengthMenu="[50,200,1000]"
                             columnVisibility="true" copy="true" excel="true" pdf="true" print="true"> 

                    <b:dataTableColumn value="#{tituloReceber.id}" label="ID" styleClass="coluna-centro" style="width: 40px;"/>
                    <b:dataTableColumn value="#{tituloReceber.cliente.nome}" label="Cliente" style="width: 200px;" />
                    <b:dataTableColumn label="Data emissão" dataType="date" data-order="#{tituloReceber.dataEmissao.toString()}" style="width: 120px;">
                        <h:outputText value="#{tituloReceber.dataEmissao}">
                            <f:convertDateTime type="both" pattern="dd/MM/yyyy HH:mm:ss" />
                        </h:outputText>	    				
                    </b:dataTableColumn>
                    <b:dataTableColumn label="Data vencimento" dataType="date" data-order="#{tituloReceber.dataVencimento.toString()}" style="width: 120px;">
                        <h:outputText value="#{tituloReceber.dataVencimento}">
                            <f:convertDateTime type="both" pattern="dd/MM/yyyy HH:mm:ss" />
                        </h:outputText>	    				
                    </b:dataTableColumn>  
                    <b:dataTableColumn label="Valor">
                        <h:outputText value="#{tituloReceber.valor}">
                            <f:convertNumber type="currency" />
                        </h:outputText>
                    </b:dataTableColumn> 
                    <b:dataTableColumn label="Saldo">
                        <h:outputText value="#{tituloReceber.saldo}">
                            <f:convertNumber type="currency" />
                        </h:outputText>
                    </b:dataTableColumn>                   
                    <b:dataTableColumn value="#{tituloReceber.documento}" label="Documento" />
                    <b:dataTableColumn value="#{tituloReceber.projeto.id}" label="Projeto" />
                    <b:dataTableColumn label="Status" style="text-align: center; width: 90px;" >
                        <b:label rendered="false" text="#{tituloReceber.status.label}" style="margin-top: 8px; background-color: #{tituloReceber.status.cor};"
                                 tinyScreen="full-width" smallScreen="full-width" mediumScreen="full-width" largeScreen="full-width" />

                        <b:label rendered="true" text="#{tituloReceber.status.label}" style="margin-top: 2px; background-color: #{tituloReceber.status.cor};"
                                 tinyScreen="full-width" smallScreen="full-width" mediumScreen="full-width" largeScreen="full-width" />
                    </b:dataTableColumn>

                    <b:dataTableColumn label="" style-class="coluna-acao-1btn" orderable="false">
                        <b:navLink outcome="/financeiro/CadastroTituloReceber" tooltip="Editar" iconAwesome="pencil" value="">
                            <f:param name="tituloReceber" value="#{tituloReceber.id}" />
                        </b:navLink>	    		
                    </b:dataTableColumn>
                </b:dataTable>

            </b:container>
        </h:form>	    
    </ui:define>
</ui:composition>