Mesure/src/main/java/com/mesure/controller/CadastroColaboradorBean.java
package com.mesure.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.mesure.enumerator.ESimNao;
import com.mesure.enumerator.ESituacaoColaborador;
import com.mesure.enumerator.ETipoAnotacaoColaborador;
import com.mesure.enumerator.ETipoColaborador;
import com.mesure.model.Colaborador;
import com.mesure.model.ColaboradorTreinamento;
import com.mesure.model.ColaboradorAdvertencia;
import com.mesure.model.ColaboradorAtestado;
import com.mesure.model.ColaboradorEquipamento;
import com.mesure.model.ColaboradorEstabilidade;
import com.mesure.model.Empresa;
import com.mesure.model.EquipamentoProtecao;
import com.mesure.model.Filial;
import com.mesure.model.Treinamento;
import com.mesure.model.Usuario;
import com.mesure.repository.ColaboradorRepository;
import com.mesure.repository.EmpresaRepository;
import com.mesure.repository.EquipamentoProtecaoRepository;
import com.mesure.repository.TreinamentoRepository;
import com.mesure.repository.UsuarioRepository;
import com.mesure.repository.filter.EmpresaFilter;
import com.mesure.security.UsuarioLogado;
import com.mesure.security.UsuarioSistema;
import com.mesure.service.ColaboradorService;
import com.mesure.util.jsf.FacesUtil;

@Named
@ViewScoped
public class CadastroColaboradorBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Inject
	private ColaboradorRepository colaboradorRepository;
	
	@Inject
	private ColaboradorService colaboradorService;
	
	@Inject
	private UsuarioRepository usuarioRepository;
	
	@Inject
	EmpresaRepository empresaRepository;
	
	@Inject
	TreinamentoRepository treinamentoRepository;
	
	@Inject
	EquipamentoProtecaoRepository equipamentoProtecaoRepository;
	
	@Inject
	@UsuarioLogado
	private UsuarioSistema usuarioLogado;	
	
	private Colaborador colaborador;
	private ColaboradorTreinamento treinamento;
	private ColaboradorAdvertencia advertencia;
	private ColaboradorAtestado atestado;
	private ColaboradorEquipamento equipamento;
	private ColaboradorEstabilidade estabilidade;
	
	private Empresa empresa;
	
	private List<Empresa> empresas;
	private List<Filial> filiais;	
	
	private List<Usuario> usuarios;
	private List<Treinamento> treinamentos;
	private List<EquipamentoProtecao> equipamentos;
		
    private List<String> cargosAutoComplete;

	public CadastroColaboradorBean() {		
		limpar();
	}
	
	public void inicializar() {
		if (this.colaborador == null) {
			limpar();
		}
		
		inicializarSituacaoColaborador();
		
		// Carrega todos os usuários ativos cadastrados
		usuarios = usuarioRepository.ativos();
		
		// carrega todas as empresas cadastradas
		empresas = empresaRepository.empresas(new EmpresaFilter());
		
		// Carrega todos os treinamentos/qualificações cadastrados
		treinamentos = treinamentoRepository.treinamentos();
		
		// Carrega todos os equipamentos de proteção individual (EPI) cadastrados
		equipamentos = equipamentoProtecaoRepository.equipamentos();
		
		// Carrega os cargos para autocomplete
		carregarCargos();
		
		// Se é um novo colaborador, ou seja, modo de inclusão
		if (colaborador != null && !colaborador.isEditando())  {
			empresa = usuarioLogado.getFilialAtiva().getEmpresa();
			colaborador.setFilial(usuarioLogado.getFilialAtiva());
		}
		
		// Carrega as filiais da empresa para apresentar no formulário
		if (empresa != null) {
			carregarFiliais();
		}	
	}
	
	public void inicializarSituacaoColaborador() {
		if (colaborador != null)  {
			if (!colaborador.isEditando()) {
				colaborador.setSituacao(ESituacaoColaborador.TRABALHANDO);
			}
		}		
	}
	
    public void carregarCargos() {
    	cargosAutoComplete = colaboradorRepository.cargosAutoComplete();
    }
    
	public void carregarFiliais() {
		filiais = null;
		
		if (empresa != null) {
			filiais = empresaRepository.filialDe(empresa);
		}		
	}    
	
	private void limpar() {
		this.colaborador = new Colaborador();
		limparTreinamento();
		limparAdvertencia();
		limparAtestado();
		limparEquipamento();
		limparEstabilidade();
		
		empresa = null;
		filiais = null;		
	}
	
	public void limparTreinamento() {
		this.treinamento = new ColaboradorTreinamento();
	}
	
	public void limparAdvertencia() {
		this.advertencia = new ColaboradorAdvertencia();
	}
	
	public void limparAtestado() {
		this.atestado = new ColaboradorAtestado();
	}
	
	public void limparEquipamento() {
		this.equipamento = new ColaboradorEquipamento();
	}
	
	public void limparEstabilidade() {
		this.estabilidade = new ColaboradorEstabilidade();
	}	
	
	public void salvar() {		
		tratarDataDesligamento();
		
		colaborador = colaboradorService.salvar(colaborador);
		
		// Se alterou o cadastro do colaborador ativo, atualiza a informação no 
		// objeto que armazena o usuário logado por conta da filial ativa
		if (this.colaborador.equals(usuarioLogado.getUsuario().getColaborador())) {
			usuarioLogado.atualizarColaborador(this.colaborador);	
		}		
		
		limpar();
		inicializarSituacaoColaborador();

		FacesUtil.addInfoMessageGrowl("Gravação efetuada com sucesso.");
	}
	
	public void incluirTreinamento() {
		if (!colaborador.getTreinamentos().contains(treinamento)) {
			treinamento.setColaborador(colaborador);
			colaborador.getTreinamentos().add(treinamento);
		}
		limparTreinamento();
	}	
		
	public void excluirTreinamento() {
		if (treinamento != null) {
			colaborador.getTreinamentos().remove(treinamento);	
		}		
	}	
	
	public void incluirAdvertencia() {
		if (!colaborador.getAdvertencias().contains(advertencia)) {
			advertencia.setColaborador(colaborador);
			colaborador.getAdvertencias().add(advertencia);
		}
		limparAdvertencia();
	}	
		
	public void excluirAdvertencia() {
		if (advertencia != null) {
			colaborador.getAdvertencias().remove(advertencia);	
		}		
	}
	
	public void incluirAtestado() {
		if (!colaborador.getAtestados().contains(atestado)) {
			atestado.setColaborador(colaborador);
			colaborador.getAtestados().add(atestado);
		}
		limparAtestado();
	}	
		
	public void excluirAtestado() {
		if (atestado != null) {
			colaborador.getAtestados().remove(atestado);	
		}		
	}
	
	public void incluirEquipamento() {
		if (!colaborador.getEquipamentos().contains(equipamento)) {
			equipamento.setColaborador(colaborador);
			colaborador.getEquipamentos().add(equipamento);
		}
		limparEquipamento();
	}	
		
	public void excluirEquipamento() {
		if (equipamento != null) {
			colaborador.getEquipamentos().remove(equipamento);	
		}		
	}
	
	public void incluirEstabilidade() {
		if (!colaborador.getEstabilidades().contains(estabilidade)) {
			estabilidade.setColaborador(colaborador);
			colaborador.getEstabilidades().add(estabilidade);
		}
		limparEstabilidade();
	}	
		
	public void excluirEstabilidade() {
		if (estabilidade != null) {
			colaborador.getEstabilidades().remove(estabilidade);	
		}		
	}
	
	public void tratarDataDesligamento() {
		if (colaborador.getSituacao() != ESituacaoColaborador.DEMITIDO) {
			colaborador.setDataDesligamento(null);
		}
	}
	
	public void onChangeSituacao() {
		tratarDataDesligamento();
	}
	
	public void onChangeEmpresa() {
		carregarFiliais();
	}	
	
	// Para carregar as opções do Enum no formulário
	public ESituacaoColaborador [] getSituacoes() {
		return ESituacaoColaborador.values();
	}
	
	// Para carregar as opções do Enum no formulário
	public ETipoColaborador [] getTipos() {
		return ETipoColaborador.values();
	}
	
	// Para carregar as opções do Enum no formulário
	public ETipoAnotacaoColaborador [] getTiposAnotacao() {
		return ETipoAnotacaoColaborador.values();
	}	
	
	// Para carregar as opções do Enum no formulário
	public ESimNao[] getOpcoesSimNao() {
		return ESimNao.values();
	}	
	
	public Colaborador getColaborador() {
		return colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
		
		if (this.colaborador != null) {
			this.empresa = this.colaborador.getFilial().getEmpresa();
		}		
	}
	
	public ColaboradorTreinamento getTreinamento() {
		return treinamento;
	}

	public void setTreinamento(ColaboradorTreinamento treinamento) {
		this.treinamento = treinamento;
	}
	
	public ColaboradorAdvertencia getAdvertencia() {
		return advertencia;
	}

	public void setAdvertencia(ColaboradorAdvertencia advertencia) {
		this.advertencia = advertencia;
	}	

	public ColaboradorAtestado getAtestado() {
		return atestado;
	}

	public void setAtestado(ColaboradorAtestado atestado) {
		this.atestado = atestado;
	}
	
	public ColaboradorEquipamento getEquipamento() {
		return equipamento;
	}

	public void setEquipamento(ColaboradorEquipamento equipamento) {
		this.equipamento = equipamento;
	}
	
	public ColaboradorEstabilidade getEstabilidade() {
		return estabilidade;
	}

	public void setEstabilidade(ColaboradorEstabilidade estabilidade) {
		this.estabilidade = estabilidade;
	}

	public Empresa getEmpresa() {
		return empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public List<Empresa> getEmpresas() {
		return empresas;
	}

	public List<Filial> getFiliais() {
		return filiais;
	}

	public List<Usuario> getUsuarios() {
		return usuarios;
	}
	
	public List<Treinamento> getTreinamentos() {
		return treinamentos;
	}
	
	public List<EquipamentoProtecao> getEquipamentos() {
		return equipamentos;
	}

	public List<String> getCargosAutoComplete() {
		return cargosAutoComplete;
	}

}

Mesure/src/main/java/com/mesure/controller/PesquisaTreinamentoBean.java
package com.mesure.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.mesure.enumerator.ELocalTreinamento;
import com.mesure.model.Fornecedor;
import com.mesure.model.Treinamento;
import com.mesure.repository.FornecedorRepository;
import com.mesure.repository.TreinamentoRepository;
import com.mesure.util.jsf.FacesUtil;

@Named
@ViewScoped
public class PesquisaTreinamentoBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Inject
	TreinamentoRepository treinamentoRepository;
	
	@Inject
	FornecedorRepository fornecedorRepository;	
	
	private List<Treinamento> treinamentos;	
	private List<Fornecedor> fornecedores;
	
	private Treinamento treinamentoSelecionado;
	
	public PesquisaTreinamentoBean() {
		limpar();
	}
	
	public void inicializar() {
		// Carrega todos os fornecedores cadastrados
		fornecedores = fornecedorRepository.fornecedores();		
	}
	
	public void salvar() {
		treinamentoSelecionado = treinamentoRepository.guardar(treinamentoSelecionado);
		limpar();
	}	
	
	public void excluir() {
		treinamentoRepository.remover(treinamentoSelecionado);
		treinamentos.remove(treinamentoSelecionado);
		
		FacesUtil.addInfoMessage("Treinamento '" + treinamentoSelecionado.getDescricao() + "' excluído com sucesso.");
	}
	
	public void pesquisar() {
		treinamentos = treinamentoRepository.treinamentos();
	}
	
	public void limpar() {
		treinamentoSelecionado = new Treinamento();
	}
	
	// Para carregar as opções do Enum no formulário
	public ELocalTreinamento [] getLocais() {
		return ELocalTreinamento.values();
	}	


	public Treinamento getTreinamentoSelecionado() {
		return treinamentoSelecionado;
	}

	public void setTreinamentoSelecionado(Treinamento treinamentoSelecionado) {
		this.treinamentoSelecionado = treinamentoSelecionado;
	}

	public List<Treinamento> getTreinamentos() {
		return treinamentos;
	}

	public List<Fornecedor> getFornecedores() {
		return fornecedores;
	}

}

Mesure/src/main/webapp/colaboradores/PesquisaColaboradores.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:b="http://bootsfaces.net/ui">

    <ui:define name="titulo">Pesquisa de colaboradores</ui:define>
    
    <ui:define name="corpo">

		<h:form id="frmpesquisa">
		
			<!-- Tela modal para confirmar a exclusão do colaborador -->
			<b:modal id="modal-confirmacao" styleClass="modal-confirmacao fade" title="Confirmação" size="modal-sm" backdrop="false">
				<p>Confirma a exclusão do registro?</p>
				<f:facet name="footer">
					<b:commandButton value="Ok" oncomplete="javascript:$('.modal-confirmacao').modal('hide');return false;" 
					    action="#{pesquisaColaboradorBean.excluir}" process="@this" update="colaboradoresTable mensagens" />										
					<b:button value="Cancelar" look="primary" dismiss="modal" onclick="return false;" />
				</f:facet>
			</b:modal>  		
		
	    	<b:container fluid="true">	    		    	
	    	<b:messages id="mensagens" />
	    	
	    	<!--<b:focus target="nome" />-->
	    	<b:defaultCommand target="pesquisar" />
	    	
	    	<br/>
	    	<b:panel>
	    		<b:commandButton value="Mostrar" id="pesquisar" action="#{pesquisaColaboradorBean.pesquisar}" look="primary" update="colaboradoresTable" size="sm" />
	    		<p:spacer width="10"/>
	    		<b:button value="Novo colaborador" outcome="/colaboradores/CadastroColaborador" look="primary" size="sm" />
	    	</b:panel>

			<!--
			<b:panel>
			<b:panelGrid colSpans="2,10">
				<h:outputLabel id="nome" value="Nome:" />
				<b:inputText span="6" value="#{pesquisaColaboradorBean.filtro.nome}" fieldSize="sm" />
			</b:panelGrid>
			</b:panel>
			-->
			
			<b:dataTable id="colaboradoresTable" value="#{pesquisaColaboradorBean.colaboradorsFiltrados}" var="colaborador" customLangUrl="#{resource['/json/pt-br.json']}"
				pageLength="100" pageLengthMenu="[10,25,50,100,250,500,1000]">
	    		<b:dataTableColumn value="#{colaborador.nome}" />
		    	
		    	<b:dataTableColumn label="Admissão" dataType="date" data-order="#{colaborador.dataAdmissao.toString()}">
	    			<h:outputText value="#{colaborador.dataAdmissao}">
	    				<f:convertDateTime pattern="dd/MM/yyyy" />
	    			</h:outputText>		    	
		    	</b:dataTableColumn>
		    	
		    	<b:dataTableColumn value="#{colaborador.cargo}" />
		    	<b:dataTableColumn value="#{colaborador.foneComercial}" label="Fone" />
		    	<b:dataTableColumn value="#{colaborador.ramal}" />
		    	<b:dataTableColumn value="#{colaborador.emailComercial}" label="E-mail" />
		    	<b:dataTableColumn value="#{colaborador.situacao.label}" label="Situação" />
		    	
		    	<b:dataTableColumn label="Desligamento">
	    			<h:outputText value="#{colaborador.dataDesligamento}">
	    				<f:convertDateTime pattern="dd/MM/yyyy" />
	    			</h:outputText>		    	
		    	</b:dataTableColumn>
		    	
		    	<b:dataTableColumn label="" style-class="coluna-acao-2btn" orderable="false">
		    		<b:navLink outcome="/colaboradores/CadastroColaborador" tooltip="Editar" iconAwesome="pencil" value="">
		    			<f:param name="colaborador" value="#{colaborador.id}" />
		    		</b:navLink>
					<p:spacer width="10"/>					
		    		<b:navCommandLink oncomplete="javascript:$('.modal-confirmacao').modal('show');return false;" tooltip="Excluir" process="@this" update="colaboradoresTable" value="">
		    			<f:setPropertyActionListener target="#{pesquisaColaboradorBean.colaboradorSelecionado}" value="#{colaborador}" />
		    			<b:iconAwesome name="remove"></b:iconAwesome>
		    		</b:navCommandLink>	    		
		    	</b:dataTableColumn>
			</b:dataTable>
			
			</b:container>
		</h:form>	    
    </ui:define>
</ui:composition>

Mesure/src/main/webapp/colaboradores/PesquisaTreinamentos.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:b="http://bootsfaces.net/ui">

    <ui:define name="titulo">Treinamentos e Qualificações</ui:define>
    
    <ui:define name="corpo">
        <f:metadata>
			<f:viewAction action="#{pesquisaTreinamentoBean.inicializar}"></f:viewAction>
		</f:metadata>    
    
    	<f:event listener="#{pesquisaTreinamentoBean.pesquisar}" type="preRenderView" />
    	
    	<script>
    		function abrirModalConfirmacao() {
    			$('.modal-confirmacao').modal('show');
    			return false;
    		}
    		
    		function fecharModalConfirmacao() {
    			$('.modal-confirmacao').modal('hide');
    			return false;    			
    		}
    		
    		function abrirModalTreinamento() {
    			$('.modal-treinamento').modal('show');
    			$('#descricao').focus();
    			configurarMascara();
    			return false;
    		}
    		
			function tratarInclusaoTreinamento() {
				if ((validationFailed) || (bfHasError)) {					
					$('#descricao').focus();
				} else {
					$('.modal-treinamento').modal('hide');						
				}
				configurarMascara();
				return false;
			}			
    	</script>

		<h:form id="frmpesquisa">
		
			<!-- Tela modal para confirmar a exclusão do treinamento -->
			<b:modal id="modal-confirmacao" styleClass="modal-confirmacao fade" title="Confirmação" size="modal-sm" backdrop="false">
				<p>Confirma a exclusão do registro?</p>
				<f:facet name="footer">
					<b:commandButton value="Ok" oncomplete="javascript:fecharModalConfirmacao()" 
					    action="#{pesquisaTreinamentoBean.excluir}"	process="@this" update="treinamentosTable mensagens" />										
					<b:button value="Cancelar" look="primary" dismiss="modal" onclick="return false;" />
				</f:facet>
			</b:modal>
			
   	    	<!-- Tela modal para inclusão/alteração dos treinamentos -->
			<b:modal id="modal-treinamento" styleClass="modal-treinamento fade" title="Cadastro de Treinamentos e Qualificações" size="modal-md" backdrop="false">
				
				<b:fetchBeanInfos id="validacao"/>
				
				<b:container fluid="true" style-class="dados">
					<b:messages id="mensagens-treinamento" />
					
					<b:row>
						<b:column span="10">
							<b:inputText label="Descrição" fieldId="descricao" maxlength="60" value="#{pesquisaTreinamentoBean.treinamentoSelecionado.descricao}" fieldSize="sm" required="true" requiredMessage="Descrição deve ser informada"/>
						</b:column>			
					</b:row>
					
					<b:row>
						<b:column span="10">
							<b:selectOneMenu label="Ministrante" value="#{pesquisaTreinamentoBean.treinamentoSelecionado.fornecedor}" fieldSize="sm">
								<f:selectItem itemLabel="Selecione" itemValue="" noSelectionOption="true" />
								<f:selectItems value="#{pesquisaTreinamentoBean.fornecedores}" var="fr" itemLabel="#{fr.nome}" itemValue="#{fr}" />
							</b:selectOneMenu>	
						</b:column>	
					</b:row>				
					
					<b:row>
						<b:column span="5">
							<b:selectOneMenu label="Local" value="#{pesquisaTreinamentoBean.treinamentoSelecionado.local}" fieldSize="sm" required="true" requiredMessage="Local deve ser informado">
								<f:selectItems value="#{pesquisaTreinamentoBean.locais}" var="lo" itemLabel="#{lo.label}" itemValue="#{lo}" />
							</b:selectOneMenu>	    			
						</b:column>
					</b:row>
					
					<b:row>
						<b:column span="3">
							<b:inputText label="Carga horária" styleClass="centesimal-3-2" value="#{pesquisaTreinamentoBean.treinamentoSelecionado.cargaHoraria}" fieldSize="sm">
		    		    		<f:facet name="prepend">
            			   			<b:iconAwesome name="clock-o"/>
					            </f:facet>
				    			<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />							
							</b:inputText>

						</b:column>
					</b:row>
				</b:container>
				
				<f:facet name="footer">
					<b:commandButton value="Ok" action="#{pesquisaTreinamentoBean.salvar}"
						process="@this @(.dados)" update="treinamentosTable mensagens-treinamento validacao @(.dados)" look="primary"
						oncomplete="javascript:tratarInclusaoTreinamento()"/>
					<b:button value="Cancelar" dismiss="modal" onclick="return false;" />
				</f:facet>
			</b:modal>			
		
	    	<b:container fluid="true">	    		    	
	    	<b:messages id="mensagens" />
	    	
	    	<br/>
	    	<b:panel>
				<b:commandButton value="Novo treinamento" size="sm" action="#{pesquisaTreinamentoBean.limpar}" process="@this" update="@(.dados)"
					oncomplete="javascript:abrirModalTreinamento()" look="primary" />
	    	</b:panel>

			<b:dataTable id="treinamentosTable" value="#{pesquisaTreinamentoBean.treinamentos}" var="treinamento" customLangUrl="#{resource['/json/pt-br.json']}" 
				pageLength="50" pageLengthMenu="[50,100,500,1000]">
				
	    		<b:dataTableColumn label="Descrição" value="#{treinamento.descricao}"  />
	    		<b:dataTableColumn label="Ministrante" value="#{treinamento.fornecedor.nome}"  />
	    		<b:dataTableColumn label="Local" value="#{treinamento.local.label}"  />
	    		<b:dataTableColumn label="Carga horária">
	    			<h:outputText value="#{treinamento.cargaHoraria}">
    					<f:convertNumber minFractionDigits="2" maxFractionDigits="2"/>
	    			</h:outputText>
	    		</b:dataTableColumn>
		    	
		    	<b:dataTableColumn label="" style-class="coluna-acao-2btn" orderable="false">    		
		    		<b:navCommandLink oncomplete="javascript:abrirModalTreinamento()" tooltip="Editar" iconAwesome="pencil" value=""
		    				process="@this" update="@(.dados)">
		    			<f:setPropertyActionListener target="#{pesquisaTreinamentoBean.treinamentoSelecionado}" value="#{treinamento}" />
		    		</b:navCommandLink>			    		
					<p:spacer width="10"/>
    				<b:navCommandLink oncomplete="javascript:abrirModalConfirmacao()" tooltip="Excluir" iconAwesome="remove" value="" 
    						process="@this" update="treinamentosTable" >
		    			<f:setPropertyActionListener target="#{pesquisaTreinamentoBean.treinamentoSelecionado}" value="#{treinamento}" />
		    		</b:navCommandLink>										
		    	</b:dataTableColumn>	
			</b:dataTable>
			
			</b:container>
		</h:form>	    
    </ui:define>
</ui:composition>