Mesure/src/main/java/com/mesure/model/Empresa.java
package com.mesure.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

@Entity
@Table(name = "empresa")
public class Empresa implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String razaoSocial;
	private String nomeFantasia;
	private String site;
	private List<Filial> filiais = new ArrayList<>();
	
	@Id
	@TableGenerator (
		name="empresa_generator",
		table="generator_id",
  		pkColumnName = "GEN_KEY",
  		valueColumnName = "GEN_VALUE",
  		pkColumnValue="empresa",
  		allocationSize=1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "empresa_generator")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@NotBlank @Size(max = 100)
	@Column(nullable = false, length = 100)
	public String getRazaoSocial() {
		return razaoSocial;
	}

	public void setRazaoSocial(String razaoSocial) {
		this.razaoSocial = razaoSocial;
	}

	@Size(max = 100) 
	@Column(length = 100)	
	public String getNomeFantasia() {
		return nomeFantasia;
	}

	public void setNomeFantasia(String nomeFantasia) {
		this.nomeFantasia = nomeFantasia;
	}
	
	@Size(max = 255)
	@Column(length = 255)
	public String getSite() {
		return site;
	}

	public void setSite(String site) {
		this.site = site;
	}	

	@OneToMany(mappedBy = "empresa", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
	public List<Filial> getFiliais() {
		return filiais;
	}

	public void setFiliais(List<Filial> filiais) {
		this.filiais = filiais;
	}

	@Transient
	public boolean isNovo() {
		return getId() == null;
	}
	
	@Transient
	public boolean isEditando() {
		return getId() != null;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Empresa other = (Empresa) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}	
	
}

Mesure/src/main/java/com/mesure/controller/CadastroEmpresaBean.java
package com.mesure.controller;

import com.mesure.enumerator.EEstado;
import com.mesure.enumerator.ESimNao;
import com.mesure.enumerator.ETipoHoraExtra100;
import com.mesure.model.Empresa;
import com.mesure.model.Filial;
import com.mesure.security.UsuarioLogado;
import com.mesure.security.UsuarioSistema;
import com.mesure.service.EmpresaService;
import com.mesure.util.jsf.FacesUtil;
import java.io.Serializable;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@ViewScoped
public class CadastroEmpresaBean implements Serializable {

    private static final long serialVersionUID = 1L;

    @Inject
    private EmpresaService empresaService;
    
	@Inject
	@UsuarioLogado
	private UsuarioSistema usuarioLogado;    

    private Empresa empresa;

    private Filial filial;

    public CadastroEmpresaBean() {
        limpar();
    }

    public void inicializar() {
        if (this.empresa == null) {
            limpar();
        }
    }

    private void limpar() {
        this.empresa = new Empresa();
        limparFilial();
    }

    public void limparFilial() {
        this.filial = new Filial();
    }

    public void salvar() {
        empresa = empresaService.salvar(empresa);
        
        // Atualiza a filial ativa para garantir que fique com a informação correta
        for (Filial f : empresa.getFiliais()) {
        	if (f.equals(usuarioLogado.getFilialAtiva())) {
        		usuarioLogado.atualizarFilial(f);
        	}
        }
        
        limpar();
        FacesUtil.addInfoMessageGrowl("Gravação efetuada com sucesso.");
    }

    public void incluirFilial() {
        if (!empresa.getFiliais().contains(filial)) {
            filial.setEmpresa(empresa);
            empresa.getFiliais().add(filial);
            limparFilial();
        }
    }

    public void excluirFilial() {
        if (filial != null) {
            // TODO - testar quando a filial estiver sendo referenciada
            empresa.getFiliais().remove(filial);
        }
    }

    // Para carregar as opções do Enum no formulário
    public EEstado[] getEstados() {
        return EEstado.values();
    }

    // Para carregar as opções do Enum no formulário
    public ESimNao[] getOpcoesSimNao() {
        return ESimNao.values();
    }

    // Para carregar as opções do Enum no formulário
    public ETipoHoraExtra100[] getTiposHora100() {
        return ETipoHoraExtra100.values();
    }

    public Empresa getEmpresa() {
        return empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public Filial getFilial() {
        return filial;
    }

    public void setFilial(Filial filial) {
        this.filial = filial;
    }

}

Mesure/src/main/java/com/mesure/controller/PesquisaEmpresaBean.java
package com.mesure.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.mesure.model.Empresa;
import com.mesure.repository.EmpresaRepository;
import com.mesure.repository.filter.EmpresaFilter;
import com.mesure.util.jsf.FacesUtil;

@Named
@ViewScoped
public class PesquisaEmpresaBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Inject
	EmpresaRepository empresaRepository;
	
	private EmpresaFilter filtro;
	private List<Empresa> empresasFiltradas;
	
	private Empresa empresaSelecionada;
	
	public PesquisaEmpresaBean() {
		filtro = new EmpresaFilter();
	}	
	
	public void excluir() {
		empresaRepository.remover(empresaSelecionada);
		empresasFiltradas.remove(empresaSelecionada);
		
		FacesUtil.addInfoMessage("Empresa '" + empresaSelecionada.getRazaoSocial() + "' excluída com sucesso.");
	}
	
	public void pesquisar() {
		empresasFiltradas = empresaRepository.empresas(filtro);
	}
		
	public EmpresaFilter getFiltro() {
		return filtro;
	}

	public List<Empresa> getEmpresasFiltradas() {
		return empresasFiltradas;
	}

	public Empresa getEmpresaSelecionada() {
		return empresaSelecionada;		
	}

	public void setEmpresaSelecionada(Empresa empresaSelecionada) {
		this.empresaSelecionada = empresaSelecionada;
	}	

}

Mesure/src/main/webapp/empresas/CadastroEmpresa.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:o="http://omnifaces.org/ui"
                xmlns:b="http://bootsfaces.net/ui">

    <ui:define name="titulo">Cadastro de empresas</ui:define>

    <ui:define name="corpo">
        <f:metadata>
            <o:viewParam name="empresa" value="#{cadastroEmpresaBean.empresa}" converter="empresaConverter" />
            <f:viewAction action="#{cadastroEmpresaBean.inicializar}"></f:viewAction>
        </f:metadata>

        <h:form id="frmCadastro">

            <!-- Tela modal para confirmar a exclusão da filial -->
            <b:modal id="modal-confirmacao" styleClass="modal-confirmacao fade" title="Confirmação" size="modal-sm" backdrop="false">
                <p>Confirma a exclusão do registro?</p>
                <f:facet name="footer">
                    <b:commandButton value="Ok" oncomplete="javascript:$('.modal-confirmacao').modal('hide');return false;" 
                                     action="#{cadastroEmpresaBean.excluirFilial}"
                                     process="@this" update="filiaisTable mensagens" />										
                    <b:button value="Cancelar" look="primary" dismiss="modal" onclick="return false;" />
                </f:facet>
            </b:modal>    	    

            <!-- Tela modal para inclusão/alteração das filiais da empresa -->
            <b:modal id="modal-filial" styleClass="modal-filial fade" title="Filial" size="modal-lg" backdrop="false">

                <b:fetchBeanInfos id="validacao"/>

                <b:container fluid="true" style-class="dados-filial">
                    <b:messages id="mensagens-filial" />
                    <b:row>
                        <b:column span="6">
                            <b:inputText label="Nome" field-id="nome" maxlength="100" value="#{cadastroEmpresaBean.filial.nome}" fieldSize="sm" required="true" requiredMessage="Nome deve ser informado" />
                        </b:column>

                        <b:column span="3">
                            <b:inputText label="CNPJ" id="cnpj" alt="cnpj" value="#{cadastroEmpresaBean.filial.cnpj}" fieldSize="sm" />
                        </b:column>	
                    </b:row>

                    <b:row>
                        <b:column span="6">
                            <b:inputText label="Logradouro" field-id="logradouro" maxlength="100" value="#{cadastroEmpresaBean.filial.logradouro}" fieldSize="sm" required="true" requiredMessage="Logradouro deve ser informado" />
                        </b:column>	
                        <b:column span="2">
                            <b:inputText label="Número" maxlength="6" alt="end-numero" value="#{cadastroEmpresaBean.filial.numero}" fieldSize="sm" />
                        </b:column>	
                    </b:row>				

                    <b:row>
                        <b:column span="6">
                            <b:inputText label="Complemento" maxlength="100" value="#{cadastroEmpresaBean.filial.complemento}" fieldSize="sm" />
                        </b:column>	
                        <b:column span="2">
                            <b:inputText label="CEP" alt="cep" value="#{cadastroEmpresaBean.filial.cep}" fieldSize="sm" />
                        </b:column>							
                    </b:row>

                    <b:row>
                        <b:column span="3">
                            <b:inputText label="Bairro" maxlength="40" value="#{cadastroEmpresaBean.filial.bairro}" fieldSize="sm" />
                        </b:column>
                        <b:column span="3">
                            <b:inputText label="Cidade" maxlength="40" value="#{cadastroEmpresaBean.filial.cidade}" fieldSize="sm" required="true" requiredMessage="Cidade deve ser informada" />
                        </b:column>
                        <b:column span="3">
                            <b:selectOneMenu label="UF" value="#{cadastroEmpresaBean.filial.uf}" fieldSize="sm" required="true" requiredMessage="UF deve ser informado">
                                <f:selectItem itemLabel="Selecione" itemValue="" noSelectionOption="true" />
                                <f:selectItems value="#{cadastroEmpresaBean.estados}" var="e" itemLabel="#{e.label}" itemValue="#{e}" />
                            </b:selectOneMenu>
                        </b:column>						
                    </b:row>

                    <b:row>
                        <b:column span="3">
                            <b:inputText styleClass="fone1" label="Fone 1" maxlength="20" value="#{cadastroEmpresaBean.filial.fone1}" fieldSize="sm" />
                        </b:column>
                        <b:column span="5">
                            <b:inputText label="E-mail contato 1" id="email1" maxlength="255" value="#{cadastroEmpresaBean.filial.email1}" fieldSize="sm" />
                        </b:column>
                    </b:row>		

                    <b:row>
                        <b:column span="3">
                            <b:inputText styleClass="fone2" label="Fone 2" maxlength="20" value="#{cadastroEmpresaBean.filial.fone2}" fieldSize="sm" />
                        </b:column>
                        <b:column span="5">
                            <b:inputText label="E-mail contato 2" id="email2" maxlength="255" value="#{cadastroEmpresaBean.filial.email2}" fieldSize="sm" />
                        </b:column>
                    </b:row>
                    
                    <b:row>
                        <b:column span="3" >
                            <b:inputText label="Horas trab. diário" styleClass="centesimal-2-2" value="#{cadastroEmpresaBean.filial.horasTrabalhoDiario}" field-size="sm">
                                <f:facet name="prepend">
                                    <b:iconAwesome name="clock-o"/>
                                </f:facet>
                                <f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
                            </b:inputText>				
                        </b:column>
                        
                        <b:column span="2">
                            <b:inputText label="Início noturna" alt="time" value="#{cadastroEmpresaBean.filial.inicioHoraNoturna}" fieldSize="sm">
                                <f:convertDateTime type="time" timeStyle="short" />
                            </b:inputText>						
                        </b:column>
                        
                        <b:column span="2">
                            <b:inputText label="Limite BH" mask="integer" maxlength="3" value="#{cadastroEmpresaBean.filial.limiteBH}" fieldSize="sm" />
                        </b:column>
                    </b:row>

					<b:row>
                        <b:column span="3">
                            <b:inputText label="Dias exec. retroativo" tooltip="Dias execução retroativo" mask="integer" maxlength="3" value="#{cadastroEmpresaBean.filial.diasExecucaoRetroativo}" fieldSize="sm" />
                        </b:column>
                                                
                        <b:column span="3">
                            <b:inputText label="Dias apont. atrasado" tooltip="Dias para apontamentos atrasados" mask="integer" maxlength="3" value="#{cadastroEmpresaBean.filial.diasApontamentoAtrasado}" fieldSize="sm" />
                        </b:column> 
                    </b:row>

                    <b:row>
                        <b:column span="4">
                            <b:selectOneMenu label="Tipo hora 100%" value="#{cadastroEmpresaBean.filial.tipoHoraExtra100}" fieldSize="sm" required="true" requiredMessage="Tipo hora 100% deve ser informado">
                                <f:selectItem itemLabel="Selecione" itemValue="" noSelectionOption="true" />
                                <f:selectItems value="#{cadastroEmpresaBean.tiposHora100}" var="item" itemLabel="#{item.label}" itemValue="#{item}" />
                            </b:selectOneMenu>
                        </b:column>
                        <b:column span="2">
                            <b:selectOneMenu label="Filtrar projetos" value="#{cadastroEmpresaBean.filial.filtrarProjetos}" fieldSize="sm" required="true" requiredMessage="Filtrar projetos deve ser informado">
                                <f:selectItems value="#{cadastroEmpresaBean.opcoesSimNao}" var="item" itemLabel="#{item.label}" itemValue="#{item}" />
                            </b:selectOneMenu>
                        </b:column>
                    </b:row>                    

                </b:container>

                <f:facet name="footer">
                    <b:commandButton value="Ok" id="btn-gravar"  action="#{cadastroEmpresaBean.incluirFilial}"
                                     process="@this @(.dados-filial)" update="filiaisTable mensagens-filial validacao @(.dados-filial)" look="primary" 
                                     oncomplete="javascript:if(!validationFailed){$('.modal-filial').modal('hide');return false;}"/>										
                    <b:button value="Cancelar" dismiss="modal" onclick="return false;" />
                </f:facet>
            </b:modal>    	    

            <b:container fluid="true">

                <h3>Cadastro de empresas</h3>

                <b:messages id="mensagens" info-class="message-info-hidden" />
                <p:growl autoUpdate="true" for="message-growl" life="2000" showDetail="true" showSummary="false" />

                <b:focus target="raz-social" />
                <b:defaultCommand target="gravar" />	    	

                <b:panel>
                    <b:button value="Nova empresa" outcome="/empresas/CadastroEmpresa" look="primary" size="sm" />
                    <p:spacer width="10"/>
                    <b:commandButton value="Gravar" id="gravar" action="#{cadastroEmpresaBean.salvar}" look="primary" size="sm"
                                     process="@this @(.dados)" update="filiaisTable mensagens @(.dados)" oncomplete="javascript:configurarMascara();" />	    		
                    <b:button value="Fechar" outcome="/empresas/PesquisaEmpresas" look="primary" style="float: right" size="sm" />
                </b:panel>

                <b:panel>

                    <b:row styleClass="dados">
                        <b:column span="4">
                            <b:inputText label="Razão social" id="raz-social" maxlength="100" value="#{cadastroEmpresaBean.empresa.razaoSocial}" fieldSize="sm" required="true" requiredMessage="Razão Social deve ser informada" />
                        </b:column>
                    </b:row>

                    <b:row styleClass="dados">
                        <b:column span="4">
                            <b:inputText label="Nome fantasia" maxlength="100" value="#{cadastroEmpresaBean.empresa.nomeFantasia}" fieldSize="sm" />
                        </b:column>	
                    </b:row>

                    <b:row styleClass="dados">
                        <b:column span="4">
                            <b:inputText label="Site / URL" id="site" maxlength="255" value="#{cadastroEmpresaBean.empresa.site}" fieldSize="sm" >
                                <f:facet name="prepend">
                                    <h:outputText value="http://" />
                                </f:facet>					
                            </b:inputText>
                        </b:column>				
                    </b:row>

                </b:panel>

                <b:commandButton value="Nova Filial" look="primary" size="sm" style="margin-bottom: 8px;"
                                 oncomplete="javascript:$('.modal-filial').modal('show');configurarMascara();$('#nome').focus();return false;" 
                                 action="#{cadastroEmpresaBean.limparFilial}" process="@this" update="@(.dados-filial)">
                </b:commandButton>

                <b:dataTable id="filiaisTable" value="#{cadastroEmpresaBean.empresa.filiais}" var="filial" customLangUrl="#{resource['/json/pt-br.json']}">
                    <b:dataTableColumn value="#{filial.nome}" />
                    <b:dataTableColumn value="#{filial.cnpj}" label="CNPJ" />
                    <b:dataTableColumn value="#{filial.cidade}" />
                    <b:dataTableColumn value="#{filial.uf}" label="UF" />

                    <b:dataTableColumn label="" style-class="coluna-acao-2btn" orderable="false">
                        <b:navCommandLink value="" oncomplete="javascript:$('.modal-filial').modal('show');configurarMascara();$('#nome').focus();return false;" tooltip="Editar" process="@this" update="@(.dados-filial)" >
                            <f:setPropertyActionListener target="#{cadastroEmpresaBean.filial}" value="#{filial}" />
                            <b:iconAwesome name="pencil"></b:iconAwesome>
                        </b:navCommandLink>			    		
                        <p:spacer width="10"/>
                        <b:navCommandLink value="" oncomplete="javascript:$('.modal-confirmacao').modal('show');return false;" tooltip="Excluir" process="@this" update="filiaisTable" >
                            <f:setPropertyActionListener target="#{cadastroEmpresaBean.filial}" value="#{filial}" />
                            <b:iconAwesome name="remove"></b:iconAwesome>
                        </b:navCommandLink>										
                    </b:dataTableColumn>	    		
                </b:dataTable>

            </b:container>	
        </h:form>	
    </ui:define>
</ui:composition>

Mesure/src/main/webapp/empresas/PesquisaEmpresas.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:b="http://bootsfaces.net/ui">

    <ui:define name="titulo">Pesquisa de empresas</ui:define>
    
    <ui:define name="corpo">
    	<f:event listener="#{pesquisaEmpresaBean.pesquisar}" type="preRenderView" />

		<h:form id="frmpesquisa">
		
			<!-- Tela modal para confirmar a exclusão da empresa -->
			<b:modal id="modal-confirmacao" styleClass="modal-confirmacao fade" title="Confirmação" size="modal-sm" backdrop="false">
				<p>Confirma a exclusão do registro?</p>
				<f:facet name="footer">
					<b:commandButton value="Ok" oncomplete="javascript:$('.modal-confirmacao').modal('hide');return false;" 
					 	action="#{pesquisaEmpresaBean.excluir}" process="@this" update="empresasTable mensagens" />										
					<b:button value="Cancelar" look="primary" dismiss="modal" onclick="return false;" />
				</f:facet>
			</b:modal>  		
		
	    	<b:container fluid="true">	    		    	
	    	<b:messages id="mensagens" />
	    	
	    	<!--<b:focus target="nome" />-->
	    	<!--<b:defaultCommand target="pesquisar" />-->
	    	
	    	<br/>
	    	<b:panel>
	    		<b:button value="Nova empresa" outcome="/empresas/CadastroEmpresa" look="primary" size="sm" />
	    	</b:panel>

			<b:dataTable id="empresasTable" value="#{pesquisaEmpresaBean.empresasFiltradas}" var="empresa" customLangUrl="#{resource['/json/pt-br.json']}">
	    		<b:dataTableColumn value="#{empresa.razaoSocial}" label="Razão Social" />
		    	<b:dataTableColumn value="#{empresa.nomeFantasia}" label="Nome Fantasia" />
		    	
		    	<b:dataTableColumn label="" style-class="coluna-acao-2btn" orderable="false">
		    		<b:navLink outcome="/empresas/CadastroEmpresa" tooltip="Editar" iconAwesome="pencil" value="" >
		    			<f:param name="empresa" value="#{empresa.id}" />
		    		</b:navLink>
					<p:spacer width="10"/>					
		    		<b:navCommandLink oncomplete="javascript:$('.modal-confirmacao').modal('show');return false;" tooltip="Excluir" process="@this" update="empresasTable" value="">
		    			<f:setPropertyActionListener target="#{pesquisaEmpresaBean.empresaSelecionada}" value="#{empresa}" />
		    			<b:iconAwesome name="remove"></b:iconAwesome>
		    		</b:navCommandLink>	    		
		    	</b:dataTableColumn>
			</b:dataTable>
			
			</b:container>
		</h:form>	    
    </ui:define>
</ui:composition>