Mesure/src/main/java/com/mesure/model/Cliente.java
package com.mesure.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

import com.mesure.enumerator.ETipoPessoa;

@Entity
@Table(name = "cliente")
public class Cliente implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private String nome;
	private String apelido;
	private String cpf;
	private String cnpj;
	private String rg;
	private String inscricaoEstadual;
	private String fone1;
	private String fone2;
	private String email1;
	private String email2;
	private String nomeContato1;
	private String nomeContato2;
	private String site;
	private ETipoPessoa tipo;
	private List<EnderecoCliente> enderecos = new ArrayList<>();
	private List<Projeto> projetos = new ArrayList<>();
	
	@Id
	@TableGenerator (
		name="cliente_generator",
		table="generator_id",
  		pkColumnName = "GEN_KEY",
  		valueColumnName = "GEN_VALUE",
  		pkColumnValue="cliente",
  		allocationSize=1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "cliente_generator")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@NotBlank @Size(max = 100)
	@Column(nullable = false, length = 100)
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Size(max = 100) 
	@Column(length = 100)
	public String getApelido() {
		return apelido;
	}

	public void setApelido(String apelido) {
		this.apelido = apelido;
	}
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 10)
	public ETipoPessoa getTipo() {
		return tipo;
	}

	public void setTipo(ETipoPessoa tipo) {
		this.tipo = tipo;
	}
	
	@Size(max = 14)
	@Column(length = 14)
	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Size(max = 18) 
	@Column(length = 18)
	public String getCnpj() {
		return cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@Size(max = 15)
	@Column(length = 15)	
	public String getRg() {
		return rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}

	@Size(max = 14)
	@Column(name = "ins_estadual", length = 14)	
	public String getInscricaoEstadual() {
		return inscricaoEstadual;
	}

	public void setInscricaoEstadual(String inscricaoEstadual) {
		this.inscricaoEstadual = inscricaoEstadual;
	}

	@Size(max = 20)
	@Column(length = 20)
	public String getFone1() {
		return fone1;
	}

	public void setFone1(String fone1) {
		this.fone1 = fone1;
	}

	@Size(max = 20)
	@Column(length = 20)	
	public String getFone2() {
		return fone2;
	}

	public void setFone2(String fone2) {
		this.fone2 = fone2;
	}

	@Size(max = 255)
	@Column(length = 255)
	@Email
	public String getEmail1() {
		return email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	@Size(max = 255)
	@Column(length = 255)
	@Email
	public String getEmail2() {
		return email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}
	
	@Size(max = 255)
	@Column(name = "nome_contato1", length = 255)
	public String getNomeContato1() {
		return nomeContato1;
	}

	public void setNomeContato1(String nomeContato1) {
		this.nomeContato1 = nomeContato1;
	}

	@Size(max = 255)
	@Column(name = "nome_contato2", length = 255)
	public String getNomeContato2() {
		return nomeContato2;
	}

	public void setNomeContato2(String nomeContato2) {
		this.nomeContato2 = nomeContato2;
	}

	@Size(max = 255)
	@Column(length = 255)
	public String getSite() {
		return site;
	}

	public void setSite(String site) {
		this.site = site;
	}
	
	@OneToMany(mappedBy = "cliente", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
	public List<EnderecoCliente> getEnderecos() {
		return enderecos;
	}
	
	public void setEnderecos(List<EnderecoCliente> enderecos) {
		this.enderecos = enderecos;
	}
	
	@OneToMany(mappedBy = "cliente", fetch = FetchType.LAZY)	
	public List<Projeto> getProjetos() {
		return projetos;
	}
	
	public void setProjetos(List<Projeto> projetos) {
		this.projetos = projetos;
	}
	
	@Transient
	public String getNomeComInscricao() {
		String retorno = this.getNome();
		if (this.getTipo().equals(ETipoPessoa.FISICA)) {
			retorno += (StringUtils.isBlank(this.getCpf()) ? "" : " - " + this.getCpf());	
		} else {
			retorno += (StringUtils.isBlank(this.getCnpj()) ? "" : " - " + this.getCnpj());
		}
		return retorno;
	}

	@Transient
	public boolean isNovo() {
		return getId() == null;
	}
	
	@Transient
	public boolean isEditando() {
		return getId() != null;
	}	
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cliente other = (Cliente) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

Mesure/src/main/java/com/mesure/controller/CadastroClienteBean.java
package com.mesure.controller;

import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.mesure.enumerator.EEstado;
import com.mesure.enumerator.ETipoEndereco;
import com.mesure.enumerator.ETipoPessoa;
import com.mesure.model.Cliente;
import com.mesure.model.EnderecoCliente;
import com.mesure.service.ClienteService;
import com.mesure.util.jsf.FacesUtil;

@Named
@ViewScoped
public class CadastroClienteBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Inject
	private ClienteService clienteService;

	private Cliente cliente;	
	private EnderecoCliente endereco;
	
	private boolean pessoaJuridica;
	
	public CadastroClienteBean() {		
		limpar();		
	}
	
	public void inicializar() {
		if (this.cliente == null) {
			limpar();
		}
		onChangeTipo();
	}
	
	private void limpar() {
		this.cliente = new Cliente();
		this.cliente.setTipo(ETipoPessoa.FISICA);
		limparEndereco();
	}
	
	public void limparEndereco() {
		this.endereco = new EnderecoCliente();
	}
	
	public void salvar() {
		cliente = clienteService.salvar(cliente);
		limpar();

		FacesUtil.addInfoMessageGrowl("Gravação efetuada com sucesso.");
	}
	
	public void incluirEndereco() {
		if (!cliente.getEnderecos().contains(endereco)) {
			endereco.setCliente(cliente);
			cliente.getEnderecos().add(endereco);
			limparEndereco();
		}		
	}	
		
	public void excluirEndereco() {
		// TODO - testar quando o endereço estiver sendo referenciado
		if (endereco != null) {
			cliente.getEnderecos().remove(endereco);	
		}		
	}
	
	public boolean isPessoaJuridica() {
		return pessoaJuridica;
	}	
	
	public void onChangeTipo() {
		pessoaJuridica = (cliente.getTipo().equals(ETipoPessoa.JURIDICA));
		
		if (pessoaJuridica) {
			cliente.setCpf(null);
			cliente.setRg(null);
		} else {
			cliente.setCnpj(null);
			cliente.setInscricaoEstadual(null);
		}
	}	
	
	// Para carregar as opções do Enum no formulário
	public ETipoPessoa[] getTiposPessoa() {
		return ETipoPessoa.values();
	}
	
	// Para carregar as opções do Enum no formulário
	public EEstado[] getEstados() {
		return EEstado.values();
	}
	
	// Para carregar as opções do Enum no formulário
	public ETipoEndereco[] getTiposEndereco() {
		return ETipoEndereco.values();
	}		
	
	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public EnderecoCliente getEndereco() {
		return endereco;
	}

	public void setEndereco(EnderecoCliente endereco) {
		this.endereco = endereco;
	}
}

Mesure/src/main/java/com/mesure/controller/PesquisaClienteBean.java
package com.mesure.controller;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;

import javax.faces.FacesException;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.mesure.model.Cliente;
import com.mesure.repository.ClienteRepository;
import com.mesure.repository.filter.ClienteFilter;
import com.mesure.util.jsf.FacesUtil;

@Named
@ViewScoped
public class PesquisaClienteBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Inject
	ClienteRepository clienteRepository;
	
	private ClienteFilter filtro;
	private List<Cliente> clientesFiltrados;
	
	private Cliente clienteSelecionado;
	
	public PesquisaClienteBean() {
		filtro = new ClienteFilter();
	}	
	
	public void redirect() {
		String page = "/clientes/CadastroCliente.xhtml";
		try {
			FacesContext facesContext = FacesContext.getCurrentInstance();
			ExternalContext externalContext = facesContext.getExternalContext();
			String contextPath = externalContext.getRequestContextPath();
	
			externalContext.redirect(contextPath + page);
			facesContext.responseComplete();
		} catch (IOException e) {
			throw new FacesException(e);
		}
	}	
	
	public String redirect2() {
		return "/clientes/CadastroCliente.xhtml";
	}
	
	public void excluir() {
		clienteRepository.remover(clienteSelecionado);
		clientesFiltrados.remove(clienteSelecionado);
		
		FacesUtil.addInfoMessage("Cliente '" + clienteSelecionado.getNome() + "' excluído com sucesso.");
	}
	
	public void pesquisar() {
		clientesFiltrados = clienteRepository.filtrados(filtro);
	}
		
	public ClienteFilter getFiltro() {
		return filtro;
	}

	public List<Cliente> getClientesFiltrados() {
		return clientesFiltrados;
	}

	public Cliente getClienteSelecionado() {
		return clienteSelecionado;		
	}

	public void setClienteSelecionado(Cliente clienteSelecionado) {
		this.clienteSelecionado = clienteSelecionado;
	}	
}

Mesure/src/main/webapp/clientes/CadastroCliente.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:o="http://omnifaces.org/ui"
    xmlns:b="http://bootsfaces.net/ui">

    <ui:define name="titulo">Cadastro de clientes</ui:define>
    
    <ui:define name="corpo">
        <f:metadata>
        	<o:viewParam name="cliente" value="#{cadastroClienteBean.cliente}" converter="clienteConverter"/>
			<f:viewAction action="#{cadastroClienteBean.inicializar}"></f:viewAction>
		</f:metadata>
		
   	    <h:form id="frmCadastro">
   	    
			<!-- Tela modal para confirmar a exclusão do endereço -->
			<b:modal id="modal-confirmacao" styleClass="modal-confirmacao fade" title="Confirmação" size="modal-sm" backdrop="false">
				<p>Confirma a exclusão do registro?</p>
				<f:facet name="footer">
					<b:commandButton value="ok" oncomplete="javascript:$('.modal-confirmacao').modal('hide');return false;" 
						action="#{cadastroClienteBean.excluirEndereco}"
						process="@this" update="enderecosTable mensagens" />										
					<b:button value="Cancelar" look="primary" dismiss="modal" onclick="return false;" />
				</f:facet>
			</b:modal>    	    
   	    
   	    	<!-- Tela modal para inclusão/alteração dos endereços do cliente -->
			<b:modal id="modal-endereco" styleClass="modal-endereco fade" title="Endereço" size="modal-lg" backdrop="false">
				
				<b:fetchBeanInfos id="validacao"/>
				
				<b:container fluid="true" style-class="dados-endereco">
					<b:messages id="mensagens-endereco" />
					<b:row>
						<b:column span="3">
							<b:selectOneMenu label="Finalidade" value="#{cadastroClienteBean.endereco.tipoEndereco}" fieldSize="sm" required="true" requiredMessage="Finalidade deve ser informada">							
								<f:selectItems value="#{cadastroClienteBean.tiposEndereco}" var="e" itemLabel="#{e.label}" itemValue="#{e}" />
							</b:selectOneMenu>
						</b:column>						
					</b:row>
									
					<b:row>
						<b:column span="6">
							<b:inputText label="Logradouro" field-id="logradouro" maxlength="100" value="#{cadastroClienteBean.endereco.logradouro}" fieldSize="sm" required="true" requiredMessage="Logradouro deve ser informado" />
						</b:column>	
						<b:column span="2" offset="2">
							<b:inputText label="Número" maxlength="6" alt="end-numero" value="#{cadastroClienteBean.endereco.numero}" fieldSize="sm" />
						</b:column>	
					</b:row>				
				
					<b:row>
						<b:column span="6">
							<b:inputText label="Complemento" maxlength="100" value="#{cadastroClienteBean.endereco.complemento}" fieldSize="sm" />
						</b:column>	
						<b:column span="2" offset="2">
							<b:inputText label="CEP" alt="cep" value="#{cadastroClienteBean.endereco.cep}" fieldSize="sm" />
						</b:column>							
					</b:row>

					<b:row>
						<b:column span="4">
							<b:inputText label="Bairro" maxlength="40" value="#{cadastroClienteBean.endereco.bairro}" fieldSize="sm" />
						</b:column>
						<b:column span="4">
							<b:inputText label="Cidade" maxlength="40" value="#{cadastroClienteBean.endereco.cidade}" fieldSize="sm" required="true" requiredMessage="Cidade deve ser informada" />
						</b:column>
						<b:column span="3">
							<b:selectOneMenu label="UF" value="#{cadastroClienteBean.endereco.uf}" fieldSize="sm" required="true" requiredMessage="UF deve ser informado">
								<f:selectItem itemLabel="Selecione" itemValue="" noSelectionOption="true" />
								<f:selectItems value="#{cadastroClienteBean.estados}" var="e" itemLabel="#{e.label}" itemValue="#{e}" />
							</b:selectOneMenu>
						</b:column>						
					</b:row>
				</b:container>
				
				<f:facet name="footer">
					<b:commandButton value="Ok" id="btn-gravar"  action="#{cadastroClienteBean.incluirEndereco}"
						process="@this @(.dados-endereco)" update="enderecosTable mensagens-endereco validacao @(.dados-endereco)" look="primary" 
						oncomplete="javascript:if(!validationFailed){$('.modal-endereco').modal('hide');return false;}configurarMascara();"/>										
					<b:button value="Cancelar" dismiss="modal" onclick="return false;" />
				</f:facet>
			</b:modal>    	    
   	    
	   		<b:container fluid="true">
	   		
	   		<h3>Cadastro de clientes</h3>
	   		
	   		<b:messages id="mensagens" info-class="message-info-hidden" />
	   		<p:growl autoUpdate="true" for="message-growl" life="2000" showDetail="true" showSummary="false" />
	    	
	    	<b:focus target="nome" />
	    	<b:defaultCommand target="gravar" />	    	
	    		    	
	    	<b:panel>
	    		<b:button value="Novo cliente" outcome="/clientes/CadastroCliente" look="primary" size="sm" />
	    		<p:spacer width="10"/>
	    		<b:commandButton value="Gravar" id="gravar" action="#{cadastroClienteBean.salvar}" look="primary" size="sm"
	    			process="@this @(.dados)" update="enderecosTable mensagens @(.dados)" oncomplete="javascript:configurarMascara();" />	    		
	    		<b:button value="Fechar" outcome="/clientes/PesquisaClientes" look="primary" style="float: right" size="sm" />
	    	</b:panel>

			<b:panel>

			<b:row styleClass="dados">
				<b:column span="4">
					<b:inputText label="Nome" id="nome" maxlength="100" value="#{cadastroClienteBean.cliente.nome}" fieldSize="sm" required="true" requiredMessage="Nome deve ser informado"/>
				</b:column>
			</b:row>
			
			<b:row styleClass="dados">
				<b:column span="4">
					<b:inputText label="Apelido" id="apelido" maxlength="100" value="#{cadastroClienteBean.cliente.apelido}" fieldSize="sm" />
				</b:column>	
			</b:row>
			
			<b:row styleClass="dados">
				<b:column span="2">
					<b:selectOneMenu label="Pessoa" id="pessoa" value="#{cadastroClienteBean.cliente.tipo}" fieldSize="sm" required="true" requiredMessage="Pessoa deve ser informada"
						onchange="ajax:cadastroClienteBean.onChangeTipo()" process="@this" update="cpf rg cnpj insc-estadual">
						<f:selectItem itemLabel="Selecione" itemValue="" noSelectionOption="true" />
						<f:selectItems value="#{cadastroClienteBean.tiposPessoa}" var="t" itemLabel="#{t.label}" itemValue="#{t}" />
					</b:selectOneMenu>
				</b:column>				
			</b:row>
			
			<b:row styleClass="dados">
				<b:column span="2">
					<b:inputText label="CPF" id="cpf" alt="cpf" value="#{cadastroClienteBean.cliente.cpf}" fieldSize="sm" disabled="#{cadastroClienteBean.pessoaJuridica}"/>
				</b:column>
				<b:column span="2">
					<b:inputText label="RG" id="rg" maxlength="15" value="#{cadastroClienteBean.cliente.rg}" fieldSize="sm" disabled="#{cadastroClienteBean.pessoaJuridica}"/>
				</b:column>	
			</b:row>
			
			<b:row styleClass="dados">
				<b:column span="2">
					<b:inputText label="CNPJ" id="cnpj" alt="cnpj" value="#{cadastroClienteBean.cliente.cnpj}" fieldSize="sm" disabled="#{!cadastroClienteBean.pessoaJuridica}"/>
				</b:column>
				<b:column span="2">
					<b:inputText label="Inscrição Estadual" id="insc-estadual" maxlength="14" value="#{cadastroClienteBean.cliente.inscricaoEstadual}" fieldSize="sm" disabled="#{!cadastroClienteBean.pessoaJuridica}"/>
				</b:column>
			</b:row>
			
			<b:row styleClass="dados">
				<b:column span="2">
					<b:inputText styleClass="fone1" label="Fone 1" maxlength="20" value="#{cadastroClienteBean.cliente.fone1}" fieldSize="sm" />
				</b:column>
				<b:column span="3">
					<b:inputText label="E-mail contato 1" id="email1" maxlength="255" value="#{cadastroClienteBean.cliente.email1}" fieldSize="sm" />
				</b:column>
				<b:column span="3">
					<b:inputText label="Nome contato 1" maxlength="255" value="#{cadastroClienteBean.cliente.nomeContato1}" fieldSize="sm" />
				</b:column>
			</b:row>		
			
			<b:row styleClass="dados">
				<b:column span="2">
					<b:inputText styleClass="fone2" label="Fone 2" maxlength="20" value="#{cadastroClienteBean.cliente.fone2}" fieldSize="sm" />
				</b:column>
				<b:column span="3">
					<b:inputText label="E-mail contato 2" id="email2" maxlength="255" value="#{cadastroClienteBean.cliente.email2}" fieldSize="sm" />
				</b:column>
				<b:column span="3">
					<b:inputText label="Nome contato 2" maxlength="255" value="#{cadastroClienteBean.cliente.nomeContato2}" fieldSize="sm" />
				</b:column>				
			</b:row>
			
			<b:row styleClass="dados">
				<b:column span="4">
					<b:inputText label="Site / URL" id="site" maxlength="255" value="#{cadastroClienteBean.cliente.site}" fieldSize="sm" >
        	    		<f:facet name="prepend">
    	    	        	<h:outputText value="http://" />
	           		 	</f:facet>					
					</b:inputText>
				</b:column>				
			</b:row>
			
			</b:panel>
			
			<b:commandButton value="Novo endereço" look="primary" size="sm" style="margin-bottom: 8px;"
				oncomplete="javascript:$('.modal-endereco').modal('show');configurarMascara();$('#logradouro').focus();return false;" 
				action="#{cadastroClienteBean.limparEndereco}" process="@this" update="@(.dados-endereco)">
			</b:commandButton>
			
			<b:dataTable id="enderecosTable" value="#{cadastroClienteBean.cliente.enderecos}" var="endereco" customLangUrl="#{resource['/json/pt-br.json']}"
				responsive="true">
	    		<b:dataTableColumn value="#{endereco.tipoEndereco}" label="Uso" />
	    		<b:dataTableColumn value="#{endereco.logradouro}" />
	    		<b:dataTableColumn value="#{endereco.numero}" />
	    		<b:dataTableColumn value="#{endereco.bairro}" />
	    		<b:dataTableColumn value="#{endereco.cidade}" />
	    		<b:dataTableColumn value="#{endereco.uf}" label="UF" />
	    		<b:dataTableColumn value="#{endereco.cep}" label="CEP" />
	    		
		    	<b:dataTableColumn label="" style-class="coluna-acao-2btn" orderable="false">    		
		    		<!-- TODO - Ajustar a edição quando anteriormente clicou em "Novo endereço" e tentou gravar com os campos em branco -->		    		
		    		<b:navCommandLink value="" oncomplete="javascript:$('.modal-endereco').modal('show');configurarMascara();$('#logradouro').focus();return false;" tooltip="Editar" process="@this" update="@(.dados-endereco)" >
		    			<f:setPropertyActionListener target="#{cadastroClienteBean.endereco}" value="#{endereco}" />
		    			<b:iconAwesome name="pencil"></b:iconAwesome>
		    		</b:navCommandLink>			    		
					<p:spacer width="10"/>
		    		<b:navCommandLink value="" oncomplete="javascript:$('.modal-confirmacao').modal('show');return false;" tooltip="Excluir" process="@this" update="enderecosTable" >
		    			<f:setPropertyActionListener target="#{cadastroClienteBean.endereco}" value="#{endereco}" />
		    			<b:iconAwesome name="remove"></b:iconAwesome>
		    		</b:navCommandLink>										
		    	</b:dataTableColumn>	    		
			</b:dataTable>
			
			</b:container>	
		</h:form>	
    </ui:define>
</ui:composition>

Mesure/src/main/webapp/clientes/PesquisaClientes.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:b="http://bootsfaces.net/ui">

    <ui:define name="titulo">Pesquisa de clientes</ui:define>
    
    <ui:define name="corpo">

		<h:form id="frmpesquisa">
		
			<!-- Tela modal para confirmar a exclusão do cliente -->
			<b:modal id="modal-confirmacao" styleClass="modal-confirmacao fade" title="Confirmação" size="modal-sm" backdrop="false">
				<p>Confirma a exclusão do registro?</p>
				<f:facet name="footer">
					<b:commandButton value="Ok" oncomplete="javascript:$('.modal-confirmacao').modal('hide');return false;" 
					    action="#{pesquisaClienteBean.excluir}"	process="@this" update="clientesTable mensagens" />										
					<b:button value="Cancelar" look="primary" dismiss="modal" onclick="return false;" />
				</f:facet>
			</b:modal>  		
		
	    	<b:container fluid="true">	    		    	
	    	<b:messages id="mensagens" />
	    	
	    	<!--<b:focus target="nome" />-->
	    	<b:defaultCommand target="pesquisar" />
	    	
	    	<br/>
	    	<b:panel>
	    		<b:commandButton value="Mostrar" id="pesquisar" action="#{pesquisaClienteBean.pesquisar}" look="primary" update="clientesTable" size="sm" />
	    		<p:spacer width="10"/>
	    		<b:button value="Novo cliente" outcome="/clientes/CadastroCliente" look="primary" size="sm" />
	    	</b:panel>

			<!--
			<b:panel>
			<b:panelGrid colSpans="2,10">
				<h:outputLabel id="nome" value="Nome:" />
				<b:inputText span="6" value="#{pesquisaClienteBean.filtro.nome}" fieldSize="sm" />
			</b:panelGrid>
			</b:panel>
			-->
			
			<b:dataTable id="clientesTable" value="#{pesquisaClienteBean.clientesFiltrados}" var="cliente" customLangUrl="#{resource['/json/pt-br.json']}"> 
				
				<b:dataTableColumn value="#{cliente.id}" label="ID" styleClass="coluna-centro" />
	    		<b:dataTableColumn value="#{cliente.nome}" label="Nome" />
		    	<b:dataTableColumn value="#{cliente.tipo}" label="Pessoa" />
		    	<b:dataTableColumn value="#{cliente.cpf}" label="CPF" />
		    	<b:dataTableColumn value="#{cliente.cnpj}" label="CNPJ" />
		    	<b:dataTableColumn value="#{cliente.fone1}" label="Fone" />
		    	<b:dataTableColumn value="#{cliente.email1}" label="E-mail" />
		    	
		    	<b:dataTableColumn label="" style-class="coluna-acao-2btn" orderable="false">
		    		<b:navLink outcome="/clientes/CadastroCliente" tooltip="Editar" iconAwesome="pencil" value="">
		    			<f:param name="cliente" value="#{cliente.id}" />
		    		</b:navLink>
					<p:spacer width="10"/>					
		    		<b:navCommandLink value="" iconAwesome="remove" oncomplete="javascript:$('.modal-confirmacao').modal('show');return false;" tooltip="Excluir" process="@this" update="clientesTable" >
		    			<f:setPropertyActionListener target="#{pesquisaClienteBean.clienteSelecionado}" value="#{cliente}" />
		    		</b:navCommandLink>	    		
		    	</b:dataTableColumn>
			</b:dataTable>
			
			</b:container>
		</h:form>	    
    </ui:define>
</ui:composition>